using UnityEngine;

public class ModularCar : MonoBehaviour
{
	public float clientSteerAngle;
	public float clientDriveWheelVelocity;
	public float clientDriveWheelSlip;
	public float clientThrottle;
	public float clientBrake;
	public bool cachedEngineLowPerf;
	public bool failedStartWasEngineProblem;
	public bool wasBraking;
	public float hurtTriggerMinSpeed;
	public float cachedFuelFraction;
	public float DriveWheelVelocity;
	public float DriveWheelSlip;
	public float SteerAngle;
	public float MaxSteerAngle;
	public bool IsLockable;
	public bool clientInEditMode;
	public float _mass;
	public UnityEngine.Vector3 CentreOfMass;
	public int NumAttachedModules;
	public bool HasAnyModules;
	public int TotalSockets;
	public int NumFreeSockets;
	public float Mass;
	public bool IsKinematic;
	public bool IsEditableNow;
	public float engineStartupTime;
	public float minCollisionDamageForce;
	public float maxCollisionDamageForce;
	public float collisionDamageMultiplier;
	public bool runningClientTick;
	public bool LightsAreOn;
	public bool ShouldClientTick;
	public bool mountChaining;
	public bool checkVehicleClipping;
	public bool shouldShowHudHealth;
	public bool ignoreDamageFromOutside;
	public bool doClippingAndVisChecks;
	public float explosionForceMultiplier;
	public float explosionForceMax;
	public bool IsMovingOrOn;
	public float RealisticMass;
	public UnityEngine.Vector2 pitchClamp;
	public UnityEngine.Vector2 yawClamp;
	public bool canWieldItems;
	public bool relativeViewAngles;
	public float mountLOSVertOffset;
	public float maxMountDistance;
	public bool checkPlayerLosOnMount;
	public bool disableMeshCullingForPlayers;
	public bool allowHeadLook;
	public bool ignoreVehicleParent;
	public bool legacyDismount;
	public bool modifiesPlayerCollider;
	public bool canDrinkWhileMounted;
	public bool allowSleeperMounting;
	public bool animateClothInLocalSpace;
	public bool isMobile;
	public float SideLeanAmount;
	public bool DisableLegsMeshAtExtremeViewAnglesInFirstPersonWithEyes;
	public float FirstPersonWithArmsEyesLerp;
	public bool IsSummerDlcVehicle;
	public bool BlocksDoors;
	public float startHealth;
	public bool ShowHealthInfo;
	public bool sendsHitNotification;
	public bool sendsMeleeHitNotification;
	public bool markAttackerHostile;
	public float _health;
	public float _maxHealth;
	public float deathTime;
	public int lastNotifyFrame;
	public float SecondsSinceDeath;
	public float healthFraction;
	public float health;
	public UnityEngine.Bounds bounds;
	public bool enableSaving;
	public bool syncPosition;
	public uint parentBone;
	public ulong skinID;
	public bool HasBrain;
	public uint broadcastProtocol;
	public bool linkedToNeighbours;
	public bool isVisible;
	public bool isAnimatorVisible;
	public bool isShadowVisible;
	public bool IsNpc;
	public bool HasDisabledRenderers;
	public uint prefabID;
	public bool globalBroadcast;
	public bool globalBuildingBlock;
	public bool canTriggerParent;
	public bool isServer;
	public bool isClient;

	public class SpawnSettings : MonoBehaviour
	{
		public bool useSpawnSettings;
		public float minStartHealthPercent;
		public float maxStartHealthPercent;
	}

}